export const userData = {
    "login": "zimashima",
    "id": 52222646,
    "node_id": "MDQ6VXNlcjUyMjIyNjQ2",
    "avatar_url": "https://avatars3.githubusercontent.com/u/52222646?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zimashima",
    "html_url": "https://github.com/zimashima",
    "followers_url": "https://api.github.com/users/zimashima/followers",
    "following_url": "https://api.github.com/users/zimashima/following{/other_user}",
    "gists_url": "https://api.github.com/users/zimashima/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zimashima/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zimashima/subscriptions",
    "organizations_url": "https://api.github.com/users/zimashima/orgs",
    "repos_url": "https://api.github.com/users/zimashima/repos",
    "events_url": "https://api.github.com/users/zimashima/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zimashima/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Mashima Button",
    "company": null,
    "blog": "",
    "location": "Florida, USA",
    "email": null,
    "hireable": null,
    "bio": "A Florida woman studying Web Dev at Lambda School",
    "public_repos": 33,
    "public_gists": 0,
    "followers": 19,
    "following": 22,
    "created_at": "2019-06-25T23:03:16Z",
    "updated_at": "2019-12-03T14:34:31Z"
  }

  export const followerData = [
    {
        "login": "Courtland-Bourgeois",
        "id": 54822530,
        "node_id": "MDQ6VXNlcjU0ODIyNTMw",
        "avatar_url": "https://avatars0.githubusercontent.com/u/54822530?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Courtland-Bourgeois",
        "html_url": "https://github.com/Courtland-Bourgeois",
        "followers_url": "https://api.github.com/users/Courtland-Bourgeois/followers",
        "following_url": "https://api.github.com/users/Courtland-Bourgeois/following{/other_user}",
        "gists_url": "https://api.github.com/users/Courtland-Bourgeois/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Courtland-Bourgeois/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Courtland-Bourgeois/subscriptions",
        "organizations_url": "https://api.github.com/users/Courtland-Bourgeois/orgs",
        "repos_url": "https://api.github.com/users/Courtland-Bourgeois/repos",
        "events_url": "https://api.github.com/users/Courtland-Bourgeois/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Courtland-Bourgeois/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "ktjhan",
        "id": 7260523,
        "node_id": "MDQ6VXNlcjcyNjA1MjM=",
        "avatar_url": "https://avatars3.githubusercontent.com/u/7260523?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ktjhan",
        "html_url": "https://github.com/ktjhan",
        "followers_url": "https://api.github.com/users/ktjhan/followers",
        "following_url": "https://api.github.com/users/ktjhan/following{/other_user}",
        "gists_url": "https://api.github.com/users/ktjhan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ktjhan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ktjhan/subscriptions",
        "organizations_url": "https://api.github.com/users/ktjhan/orgs",
        "repos_url": "https://api.github.com/users/ktjhan/repos",
        "events_url": "https://api.github.com/users/ktjhan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ktjhan/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "ars394",
        "id": 54909619,
        "node_id": "MDQ6VXNlcjU0OTA5NjE5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/54909619?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ars394",
        "html_url": "https://github.com/ars394",
        "followers_url": "https://api.github.com/users/ars394/followers",
        "following_url": "https://api.github.com/users/ars394/following{/other_user}",
        "gists_url": "https://api.github.com/users/ars394/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ars394/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ars394/subscriptions",
        "organizations_url": "https://api.github.com/users/ars394/orgs",
        "repos_url": "https://api.github.com/users/ars394/repos",
        "events_url": "https://api.github.com/users/ars394/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ars394/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "WalterTheCodeGuy",
        "id": 1248796,
        "node_id": "MDQ6VXNlcjEyNDg3OTY=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/1248796?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/WalterTheCodeGuy",
        "html_url": "https://github.com/WalterTheCodeGuy",
        "followers_url": "https://api.github.com/users/WalterTheCodeGuy/followers",
        "following_url": "https://api.github.com/users/WalterTheCodeGuy/following{/other_user}",
        "gists_url": "https://api.github.com/users/WalterTheCodeGuy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/WalterTheCodeGuy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/WalterTheCodeGuy/subscriptions",
        "organizations_url": "https://api.github.com/users/WalterTheCodeGuy/orgs",
        "repos_url": "https://api.github.com/users/WalterTheCodeGuy/repos",
        "events_url": "https://api.github.com/users/WalterTheCodeGuy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/WalterTheCodeGuy/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "AJWD92",
        "id": 42694444,
        "node_id": "MDQ6VXNlcjQyNjk0NDQ0",
        "avatar_url": "https://avatars1.githubusercontent.com/u/42694444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AJWD92",
        "html_url": "https://github.com/AJWD92",
        "followers_url": "https://api.github.com/users/AJWD92/followers",
        "following_url": "https://api.github.com/users/AJWD92/following{/other_user}",
        "gists_url": "https://api.github.com/users/AJWD92/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AJWD92/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AJWD92/subscriptions",
        "organizations_url": "https://api.github.com/users/AJWD92/orgs",
        "repos_url": "https://api.github.com/users/AJWD92/repos",
        "events_url": "https://api.github.com/users/AJWD92/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AJWD92/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "crutledgedev",
        "id": 55863225,
        "node_id": "MDQ6VXNlcjU1ODYzMjI1",
        "avatar_url": "https://avatars1.githubusercontent.com/u/55863225?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/crutledgedev",
        "html_url": "https://github.com/crutledgedev",
        "followers_url": "https://api.github.com/users/crutledgedev/followers",
        "following_url": "https://api.github.com/users/crutledgedev/following{/other_user}",
        "gists_url": "https://api.github.com/users/crutledgedev/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/crutledgedev/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/crutledgedev/subscriptions",
        "organizations_url": "https://api.github.com/users/crutledgedev/orgs",
        "repos_url": "https://api.github.com/users/crutledgedev/repos",
        "events_url": "https://api.github.com/users/crutledgedev/events{/privacy}",
        "received_events_url": "https://api.github.com/users/crutledgedev/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "zimashima",
        "id": 52222646,
        "node_id": "MDQ6VXNlcjUyMjIyNjQ2",
        "avatar_url": "https://avatars3.githubusercontent.com/u/52222646?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/zimashima",
        "html_url": "https://github.com/zimashima",
        "followers_url": "https://api.github.com/users/zimashima/followers",
        "following_url": "https://api.github.com/users/zimashima/following{/other_user}",
        "gists_url": "https://api.github.com/users/zimashima/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/zimashima/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zimashima/subscriptions",
        "organizations_url": "https://api.github.com/users/zimashima/orgs",
        "repos_url": "https://api.github.com/users/zimashima/repos",
        "events_url": "https://api.github.com/users/zimashima/events{/privacy}",
        "received_events_url": "https://api.github.com/users/zimashima/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "KatrinaFinney",
        "id": 54245714,
        "node_id": "MDQ6VXNlcjU0MjQ1NzE0",
        "avatar_url": "https://avatars0.githubusercontent.com/u/54245714?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/KatrinaFinney",
        "html_url": "https://github.com/KatrinaFinney",
        "followers_url": "https://api.github.com/users/KatrinaFinney/followers",
        "following_url": "https://api.github.com/users/KatrinaFinney/following{/other_user}",
        "gists_url": "https://api.github.com/users/KatrinaFinney/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/KatrinaFinney/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/KatrinaFinney/subscriptions",
        "organizations_url": "https://api.github.com/users/KatrinaFinney/orgs",
        "repos_url": "https://api.github.com/users/KatrinaFinney/repos",
        "events_url": "https://api.github.com/users/KatrinaFinney/events{/privacy}",
        "received_events_url": "https://api.github.com/users/KatrinaFinney/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "faridhamida",
        "id": 38682091,
        "node_id": "MDQ6VXNlcjM4NjgyMDkx",
        "avatar_url": "https://avatars3.githubusercontent.com/u/38682091?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/faridhamida",
        "html_url": "https://github.com/faridhamida",
        "followers_url": "https://api.github.com/users/faridhamida/followers",
        "following_url": "https://api.github.com/users/faridhamida/following{/other_user}",
        "gists_url": "https://api.github.com/users/faridhamida/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/faridhamida/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/faridhamida/subscriptions",
        "organizations_url": "https://api.github.com/users/faridhamida/orgs",
        "repos_url": "https://api.github.com/users/faridhamida/repos",
        "events_url": "https://api.github.com/users/faridhamida/events{/privacy}",
        "received_events_url": "https://api.github.com/users/faridhamida/received_events",
        "type": "User",
        "site_admin": false
      }
    ]

